name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [src/**]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dotnet/nbgv@master
        id: nbgv
        with:
          stamp: package.json

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - run: pnpm build

      - run: npm pack && mv teams-*.tgz teamscli.tgz

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: v${{ steps.nbgv.outputs.SimpleVersion }}
        run: |
          gh release create "$VERSION" teamscli.tgz \
            --title "$VERSION" \
            --generate-notes \
            --latest
